datacast_id: "datacast-2"
sources:
  fs-source:
    driver: fs
    uri: "/data"
senders:
  fustord:
    driver: fustord
    uri: "http://fustord:18888"
    credential: { key: "key-datacast-2" }
pipes:
  sync-pipe:
    source: fs-source
    sender: fustord
