sensord_id: "sensord-1"
sources:
  fs-source:
    driver: fs
    uri: "/data"
senders:
  fustord:
    driver: fustord
    uri: "http://fustord:18888"
    credential: { key: "key-sensord-1" }
pipes:
  sync-pipe:
    source: fs-source
    sender: fustord
