sensord_id: "sensord-1"
sources:
  fs-source:
    driver: fs
    uri: "/data"
senders:
  fusion:
    driver: fusion
    uri: "http://fusion:18888"
    credential: { key: "key-sensord-1" }
pipes:
  sync-pipe:
    source: fs-source
    sender: fusion
