sources:
  src-2:
    driver: fs
    uri: "/home/huajin/fustor-1/docs"

senders:
  fustord-2:
    driver: fustord
    uri: "http://localhost:18881"
    credential:
      key: "key-1"

pipes:
  pipe-2:
    source: src-2
    sender: fustord-2
