datacast_id: "datacast-3"

sources:
  fs-source:
    driver: fs
    uri: "/data"

senders:
  fustord:
    driver: fustord
    uri: "http://fustord:18888"
    credential: { key: "key-datacast-3" }

pipes:
  sync-pipe:
    source: fs-source
    sender: fustord
