services:
  fustord:
    build:
      context: ..
      dockerfile: deploy_multi_fs_4node/Dockerfile
    ports:
      - "8101"
      - "18888"
    volumes:
      - ./fustord/config/default.yaml:/root/.fustor/fustord-config/default.yaml
    command: ["fustord", "start"]
    networks:
      - fustor-net

  datacastd1:
    build:
      context: ..
      dockerfile: deploy_multi_fs_4node/Dockerfile
    volumes:
      - ./datacastd1/config/default.yaml:/root/.fustor/datacastd-config/default.yaml
      - ./datacastd1/data:/data
    command: ["datacastd", "start"]
    depends_on:
      - fustord
    networks:
      - fustor-net

  datacastd2:
    build:
      context: ..
      dockerfile: deploy_multi_fs_4node/Dockerfile
    volumes:
      - ./datacastd2/config/default.yaml:/root/.fustor/datacastd-config/default.yaml
      - ./datacastd2/data:/data
    command: ["datacastd", "start"]
    depends_on:
      - fustord
    networks:
      - fustor-net

  datacastd3:
    build:
      context: ..
      dockerfile: deploy_multi_fs_4node/Dockerfile
    volumes:
      - ./datacastd3/config/default.yaml:/root/.fustor/datacastd-config/default.yaml
      - ./datacastd3/data:/data
    command: ["datacastd", "start"]
    depends_on:
      - fustord
    networks:
      - fustor-net

  datacastd4:
    build:
      context: ..
      dockerfile: deploy_multi_fs_4node/Dockerfile
    volumes:
      - ./datacastd4/config/default.yaml:/root/.fustor/datacastd-config/default.yaml
      - ./datacastd4/data:/data
    command: ["datacastd", "start"]
    depends_on:
      - fustord
    networks:
      - fustor-net

networks:
  fustor-net:
    driver: bridge
